- name: 拷贝内核优化模板文件
  template:
    src: sysctl.conf.j2
    dest: '/etc/sysctl.conf'
    owner: root
    group: root
    mode: 0644

- name: 修改文件最大打开数量限制
  template:
    src: limits.conf.j2
    dest: '/etc/security/limits.conf'
    owner: root
    group: root
    mode: 0644