---

- name: 保证chattr /etc/sudoer
  file:
    path: /etc/sudoers
    attr: +i
  register: sudoers_file
  changed_when: "'i' not in sudoers_file.diff.before.attributes"


- name: 保证chattr /etc/ssh/sshd_config
  file:
    path: /etc/ssh/sshd_config
    attr: +i
  register: sshd_file
  changed_when: "'i' not in sshd_file.diff.before.attributes"